### PR TITLE
Refactor svg-editor.py

### PR DESCRIPTION
**Pull request by Oakchris1955**
Fixed some bugs, replaced `elif` statements with a `match` clause and updated `README.md`

### CODE REVIEW

**Comment by TootiFruti** [comment]
Hello there, Your contribution and time is appreciated. And I have some things to talk about,
first, I have decided to put all the card details in the 'Card details.md' file, to keep README simple and clean.
Second, the refactoring is great! 
But I have some issues, I am not sure but while i was doing the replace part of the script, the `DATA.replace(arg1, arg2)` , it really did not worked, because the replace was only parsing the first line and skips everything else, that's why i used `[line.replace(f">{cmd[1]}<", f">{cmd[2]}<") for line in t] ` so that the replace will affect all the lines, can you confirm that the DATA.replace(a, b) is working? 
Everything else looks great.
And just for curiosity at line 22 `print(f"Reading file {filePath}... ", end="")`   what's the use of end here? does it makes any difference? 

Nowadays, for last few months, i have just only been doing c and rust, and now so bad at python lol, reading the script again made me laugh, who use (condition) == False, LMAO, when i was doing this i was trying '!(condition)' and then remembered that it doesnt work on python, and came up with this abomination.

**Comment by TootiFruti** [comment]
ok, i just checked the script and it works, the replace part that i was talking about, don't know why it didnt worked for me but hey, it is what it is.

and you should add another error checking in the while true loop when the command entered is just blank ( basically when spaming enter) 
```

    match cmd[0].lower():
          ~~~^^^
IndexError: list index out of range
```

**Comment by Oakchris1955** [comment]
Fixed in d9cd69e

**Comment by TootiFruti** [comment]
Great. and now at last can you also remove all the card details from the readme, as i want them to be in a separate file called 'Card details', keeping the readme small and simple.
and this will be all it.

**Pull request merged**
